[workspace]
resolver = "2"
members = ["api"]

[workspace.dependencies]
log = "0.4.22"
serde = { version = "1.0.214", features = ["derive"] }
dioxus = { version = "0.7.1" }
api = { path = "api" }

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
